server:
  port: 80

  undertow:
    io-threads: 2
    worker-threads: 36
    buffer-size: 1024
    directBuffers: true
  servlet:
    session:
      timeout: 86400

spring:
#  开启热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  transaction:
    rollback-on-commit-failure: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource

    # MySql配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vlog?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: Wjx010925
    #password: 311252

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB

  thymeleaf:
    mode: HTML5
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
    check-template-location: false

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Dao.xml
  typeAliasesPackage: com.example.blog.entity
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: error
